Fix writing with memoryviews
When I switched to using memoryviews to try to reduce allocations, all
writing broke with

   TypeError: unsupported operand type(s) for +: 'memoryview' and 'bytes'

Now, write the message and the terminator separately. Consciously *don't*
do something like

   write(msg.tobytes() + end)

since that'd just bring back the memory allocations and copies I was
trying to get rid of.

Fixes #1